### ISSUE TITLE
Common class to AWS and OpenStack cloud providers

### ISSUE THREAD

**Issue by leonardofl** [choreos/choreos_middleware#48]
A common base class, JCloudsCloudProvider, would avoid some code replication.

**Comment by fabiokon** [comment]
In fact, there's a lot of code duplication between OpenStackKeystoneCloudProvider.java and AWSCloudProvider.java.

It would be nice to create a Template Method in a common abstract superclass!

**Comment by leonardofl** [comment]
Fixed c23aad51ef34cb789806f233a86ebf786863ef7a.
And using the Template pattern : )
(done avec tfurtado)
